_BASE_: ../maskformer2_R50_bs16_50ep.yaml
MODEL:
  META_ARCHITECTURE: "VisionLanguageMaskFormerStudent"
  SEM_SEG_HEAD:
    NAME: "VisionLanguageMaskFormerHead"
  # backbone part.
  BACKBONE:
    NAME: "OpenCLIPBackbone"
  WEIGHTS: ""
  PIXEL_MEAN: [122.7709383, 116.7460125, 104.09373615]
  PIXEL_STD: [68.5005327, 66.6321579, 70.32316305]
  VL_MASK_FORMER:
    OPEN_CLIP_MODEL_NAME: "convnext_base_w_320"
    OPEN_CLIP_PRETRAINED_WEIGHTS: "laion_aesthetic_s13b_b82k_augreg"
    EMBED_DIM: 640
    GEOMETRIC_ENSEMBLE_ALPHA: 0.4
    INCLUDE_MASK_POOLINGS: False
    FREEZE_BACKBONE: True
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 200
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: False
      PANOPTIC_ON: True
      OBJECT_MASK_THRESHOLD: 0.0
  TEACHER:
    TYPE: "vl_m2f"
    EMA_DECAY: 0.999
    BURN_IN_ITERS: 0

INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 512) for x in range(5, 21)]"]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 512
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 512)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: 512  # used in dataset mapper
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_panoptic_semi_sup"

SOLVER:
  MAX_ITER: 80000
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 80000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
TEST:
  EVAL_PERIOD: 20000

UNLABELED_INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 512) for x in range(5, 21)]"]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MAX_SIZE_TRAIN: 2048
  CUTMIX_ENABLED: True
  CUTMIX_PROB: 0.5
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 512)
    SINGLE_CATEGORY_MAX_AREA: 1.0

DATASETS:
  TRAIN: ("vlm_coco_2017_train_panoptic_semi_sup_labeled_train_1_512_with_sem_seg",)
  TEST: ("vlm_coco_2017_val_panoptic_with_sem_seg",)
  TRAIN_UNLABELED: "vlm_coco_2017_train_panoptic_semi_sup_unlabeled_train_1_512_with_sem_seg"